### ISSUE TITLE
App doesnt launch

### ISSUE THREAD

**Issue by TomerGamerTV** [SyberiaK/CMDR#1]
I tried opening it couple of times but it doesn't seem to open anything. i have java installed and I'm on the latest windows 10 version i don't understand why its not working

**Comment by SyberiaK** [comment]
Please send latest log file (placed in C:\Users\[YOUR_USERNAME]\AppData\Local\CMDR\logs). I'll look into it later.

**Comment by TomerGamerTV** [comment]
There is no CMDR folder

**Comment by SyberiaK** [comment]
Sorry for late reply, I finally found the issue.
CMDR is compiled using Java 18, so you can't use older versions. Maybe I will fix that later and correct fine requirements.
For now just install newest Java.

Let me know if this answer helped you or you have other problems :)

**Comment by TomerGamerTV** [comment]
Yep it worked, for anyone that is having trouble finding the download link i placed it [here](https://www.oracle.com/java/technologies/javase/jdk18-archive-downloads.html)

**Comment by TomerGamerTV** [comment]
Where can i find the resources pack that is required to make it work?

**Comment by SyberiaK** [comment]
The resource pack generates automatically each time you launch the app. If it doesn't - make sure you specified valid path to Minecraft directory in app settings and then restart the app.
Also don't forget to enable the RP in game settings.

**Comment by SyberiaK** [comment]
[v0.2.1 patch](https://github.com/SyberiaK/CMDR/releases/tag/v0.2.1), featuring Java 8 support and RP hot-generating.

**Comment by TomerGamerTV** [comment]
Btw is it possible to change this explorer ui? it looks old and its uncomfortable to navigate
![image](https://user-images.githubusercontent.com/44266242/192639560-0bc008cc-02d2-4a0f-ab16-7c12f19cd1cb.png)
